version: 0.2

run-as: root

env:
  shell: bash
  parameter-store:
    # NPM_TOKEN: "/Credentials/NPM/access-token"
    GIT_TOKEN: "/GitHub/MyToken"
  # variables:
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 20.x
    commands:
      - echo install nodejs
  pre_build:
    on-failure: ABORT
    commands:
      - npm install
      - npm install -g ts-node

  build:
    on-failure: ABORT
    commands:
      - npx ts-node scripts/increment-package-version/main.ts  ./package.json

  post_build:
    commands:
      - git config --global user.email "horie.takehiro@outlook.jp"
      - git config --global user.name "horie.takehiro"
      - git commit -am "release version $(cat package.json | jq -r .version)"
      - git tag v$(cat package.json | jq -r .version)
      # - git merge -X theirs --allow-unrelated-histories release
      - git push https://${GITHUB_TOKEN}@github.com/horietakehiro/cfn-docgen.git main
      - git push https://${GITHUB_TOKEN}@github.com/horietakehiro/cfn-docgen.git v$(cat package.json | jq -r .version)


