version: 0.2

run-as: root

env:
  shell: bash
  parameter-store:
    NPM_TOKEN: "/Credentials/NPM/access-token"
  variables:
    NODE_OPTIONS: "--experimental-vm-modules"
  exported-variables:
    PACKAGE_NAME
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 20.x
    commands:
      - echo install nodejs
  pre_build:
    on-failure: ABORT
    commands:
      - npm ci
      - npm install -g ts-node
    
  build:
    on-failure: ABORT
    commands:
      - npm test -- --roots test/unit
      - npm test -- --roots test/functional
      - ts-node scripts/generate-cfn-ts-codes/main.ts
      - npm test -- --roots test/e2e

  post_build:
    commands:
      - npm publish --access=public
      - export PACKAGE_NAME=$(cat package.json | jq -r '(.name + "@" + .version)')
